# Site settings
title: AI in NZ Living Whitepaper
email: info@aiforum.org.nz
description: >-
  A living snapshot of the Generative AI landscape in Aotearoa New Zealand.
  Researching AI topics, using AI, for the AI community.
baseurl: ""
url: "https://www.livingwhitepaper.com"

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap

header_pages:
  - whitepaper/index.markdown
  - how-it-works.markdown
  - about.markdown

