name: Update whitepapers

on:
  workflow_dispatch: # Allow manual triggering

env:
  # This workflow sets the RESEARCH_MODEL environment variable for all jobs
  # To change the model, edit the value below or set it as a secret
  #
  # Example: RESEARCH_MODEL: o4-mini-deep-research
  #
  RESEARCH_MODEL: gpt-4.1-mini

jobs:
  update-articles:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Run livingwp update
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: uv run livingwp

      - name: Check for changes
        id: changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "changes=true" >> $GITHUB_OUTPUT
            echo "Changes detected"
          else
            echo "changes=false" >> $GITHUB_OUTPUT
            echo "No changes detected"
          fi

      - name: Create Pull Request
        if: steps.changes.outputs.changes == 'true'
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: Auto-update articles (${{ github.run_id }})"
          title: "chore: 🔄 Generate new articles"
          body: |
            This PR was automatically generated by the livingwp update process.

            ## Changes
            - Updated article content based on latest research
            - Generated on: ${{ github.run_id }}

            Please review the changes before merging.
          branch: chore/article-update-${{ github.run_number }}
          delete-branch: true
          draft: false
